### ISSUE TITLE
Enable RPi touchscreen drivers

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_rpi3a#10]
Based on a Slack comment, it looks like the RPi3A doesn't have the touchscreen drivers enabled so it won't work out of the box with Scenic. It would be nice to add this so people could make kiosks with the 3A.

**Comment by fhunleth** [comment]
On second thought, this could be broken due to the recent `input_event` release.

**Comment by lawik** [comment]
I tried adding

```
dtoverlay=rpi-ft5406
dtoverlay=rpi-backlight
```

both to the downloaded artifact and with a custom system. I confirmed the presence of the lines with ` File.read!("/boot/config.txt")` on running the device.

But it still doesn't show up in `InputEvent.enumerate`.

It does show up in `lsmod`:

`rpi_ft5406 16384 0 - Live 0x7f18e000`

**Comment by lawik** [comment]
The `rpi3` system does work for the `rpi3a` to get input event working. Same version of `input_event`.

**Comment by fhunleth** [comment]
Bummer - I really expected the `config.txt` updates to work. It's probably something really simple. I'll add this to my list to look at later this week.

**Comment by lawik** [comment]
Hopefully simple, I reserve the right to have screwed up the test somehow. I haven't made a lot of custom systems.
